### ISSUE TITLE
Root level tags are not transferred to the resulting config

### ISSUE THREAD

**Issue by servernoj** [theodo/serverless-openapi#6]
I have `custom/documentation` section of `serverless.yml` defined as follows:
``` yml
version: ...
title: ...
description: ...
tags:
  - name: public
    description: API endpoints not requiring authentication
  - name: user-level
  - name: ...
models:
  - ...
```
with `...` being properly replaced with meaningful values. After compilation, I don't see the `tags` section in the resulting `openapi.yml` file on the root level.

Note: function-level `tags` definition are properly transferred.
