### ISSUE TITLE
"examples" field does not comply with OpenAPI 3.0 Specification

### ISSUE THREAD

**Issue by ckho-wkcda** [theodo/serverless-openapi#8]
According to [OpenAPI 3.0 Specification](https://swagger.io/specification/#components-object),
the field "examples" should be a map.

Example:
```yml
examples: 
  foo:
    summary: A foo example
    value: {"foo": "bar"}
  bar:
    summary: A bar example
    value: {"bar": "baz"}
```

However, in the current implementation of this plugin, it is implemented as an array.

Ref:
In `serverless-openapi/src/DefinitionGenerator.ts`
```js
if (parameter.example) {
  parameterConfig.example = parameter.example;
// BELOW (Line 227)
} else if (parameter.examples && Array.isArray(parameter.examples)) {
// ABOVE (Line 227)
  parameterConfig.examples = parameter.examples;
}
```
```js
private attachExamples(target, config) {
// BELOW (Line 307)
  if (target.examples && Array.isArray(target.examples)) {
// ABOVE (Line 307)
    _.merge(config, { examples: _.cloneDeep(target.examples) });
  } else if (target.example) {
    _.merge(config, { example: _.cloneDeep(target.example) });
  }
}
```
